name: Update Fixed Issues

on:
  release:
    types: [published]

jobs:
  update-fixed-issues:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Extract version from release
        id: extract_version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          # Remove 'v' prefix if present
          VERSION=$(echo "$VERSION" | sed 's/^v//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release info for issue comments
        id: release_info
        run: |
          # Get last two releases
          RELEASES=$(gh api repos/${{ github.repository }}/releases --jq ".[0:2].[].name")
          LATEST_RELEASE=$(echo "${RELEASES}" | head -1)
          PREV_RELEASE=$(echo "${RELEASES}" | tail -1)

          echo "latest=$LATEST_RELEASE" >> $GITHUB_OUTPUT
          echo "previous=$PREV_RELEASE" >> $GITHUB_OUTPUT

          RELEASE_URL=$(gh release view v${{ steps.extract_version.outputs.version }} --json url | jq -r ".url")
          echo "release_url=$RELEASE_URL" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on fixed issues
        run: |
          # Get PRs included in this release
          START=$(gh release view ${{ steps.release_info.outputs.previous }} --json publishedAt | jq -r ".publishedAt")
          END=$(gh release view ${{ steps.release_info.outputs.latest }} --json publishedAt | jq -r ".publishedAt")
          PRS=$(gh pr list --search="merged:$START..$END" --json="number" | jq -r ".[].number")

          # For each PR, get linked issues and comment
          for PR in $PRS; do
            ISSUES=$(gh pr view $PR --json "closingIssuesReferences" | jq -r ".closingIssuesReferences[].number")
            for ISSUE in $ISSUES; do
              if [ ! -z "$ISSUE" ]; then
                gh issue comment $ISSUE --body "🎉 This issue has been resolved in [${{ steps.release_info.outputs.latest }}](${{ steps.release_info.outputs.release_url }})!"
              fi
            done
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}